/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author BVAJ
 */
public class VistaNuevoPassword extends javax.swing.JFrame {

    /**
     * Creates new form VistaNuevoPassword
     */
    public VistaNuevoPassword() {
        initComponents();
       ocultarPass1.setVisible(false);
       ocultarPass2.setVisible(false);
       ocultarPass3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalirDePass = new javax.swing.JButton();
        txtPassConfirmar = new javax.swing.JPasswordField();
        txtPassAnterior = new javax.swing.JPasswordField();
        txtPassNuevo = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtError = new javax.swing.JLabel();
        mostrarPass1 = new javax.swing.JLabel();
        ocultarPass1 = new javax.swing.JLabel();
        mostrarPass2 = new javax.swing.JLabel();
        mostrarPass3 = new javax.swing.JLabel();
        ocultarPass2 = new javax.swing.JLabel();
        ocultarPass3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password anterior");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirmar password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password nuevo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(102, 153, 255));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 124, -1));

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, 57));

        btnSalirDePass.setBackground(new java.awt.Color(51, 51, 51));
        btnSalirDePass.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        btnSalirDePass.setForeground(new java.awt.Color(102, 153, 255));
        btnSalirDePass.setText("Regresar");
        btnSalirDePass.setBorder(null);
        btnSalirDePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirDePassActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalirDePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 126, 57));

        txtPassConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        txtPassConfirmar.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        txtPassConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        txtPassConfirmar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassConfirmar.setBorder(null);
        txtPassConfirmar.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassConfirmar.setEchoChar('*');
        txtPassConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 216, 32));

        txtPassAnterior.setBackground(new java.awt.Color(51, 51, 51));
        txtPassAnterior.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        txtPassAnterior.setForeground(new java.awt.Color(255, 255, 255));
        txtPassAnterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassAnterior.setBorder(null);
        txtPassAnterior.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassAnterior.setEchoChar('*');
        jPanel1.add(txtPassAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 216, 34));

        txtPassNuevo.setBackground(new java.awt.Color(51, 51, 51));
        txtPassNuevo.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        txtPassNuevo.setForeground(new java.awt.Color(255, 255, 255));
        txtPassNuevo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassNuevo.setBorder(null);
        txtPassNuevo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassNuevo.setEchoChar('*');
        txtPassNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 216, 33));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cambio de password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 24, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 216, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 216, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 216, 10));

        txtError.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 441, 312, 31));

        mostrarPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vista.png"))); // NOI18N
        mostrarPass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarPass1MouseClicked(evt);
            }
        });
        jPanel1.add(mostrarPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        ocultarPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/esconder.png"))); // NOI18N
        ocultarPass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarPass1MouseClicked(evt);
            }
        });
        jPanel1.add(ocultarPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        mostrarPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vista.png"))); // NOI18N
        mostrarPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarPass2MouseClicked(evt);
            }
        });
        jPanel1.add(mostrarPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        mostrarPass3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vista.png"))); // NOI18N
        mostrarPass3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarPass3MouseClicked(evt);
            }
        });
        jPanel1.add(mostrarPass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        ocultarPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/esconder.png"))); // NOI18N
        ocultarPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarPass2MouseClicked(evt);
            }
        });
        jPanel1.add(ocultarPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        ocultarPass3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/esconder.png"))); // NOI18N
        ocultarPass3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarPass3MouseClicked(evt);
            }
        });
        jPanel1.add(ocultarPass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        controlador.Controlador.BtnCancelarCambio();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        controlador.Controlador.BtnAceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnSalirDePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirDePassActionPerformed
        controlador.Controlador.BtnRegresar();
    }//GEN-LAST:event_btnSalirDePassActionPerformed

    private void txtPassConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassConfirmarActionPerformed

    private void txtPassNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassNuevoActionPerformed

    private void mostrarPass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarPass1MouseClicked
        
        mostrarPass1.setVisible(false);
        ocultarPass1.setVisible(true);
        txtPassAnterior.setEchoChar((char) 0);
    }//GEN-LAST:event_mostrarPass1MouseClicked

    private void mostrarPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarPass2MouseClicked
        mostrarPass2.setVisible(false);
        ocultarPass2.setVisible(true);
        txtPassNuevo.setEchoChar((char) 0);
    }//GEN-LAST:event_mostrarPass2MouseClicked

    private void mostrarPass3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarPass3MouseClicked
        mostrarPass3.setVisible(false);
        ocultarPass3.setVisible(true);
        txtPassConfirmar.setEchoChar((char) 0);
    }//GEN-LAST:event_mostrarPass3MouseClicked

    private void ocultarPass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarPass1MouseClicked
        
        mostrarPass1.setVisible(true);
        ocultarPass1.setVisible(false);
        txtPassAnterior.setEchoChar('*');
    }//GEN-LAST:event_ocultarPass1MouseClicked

    private void ocultarPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarPass2MouseClicked
        mostrarPass2.setVisible(true);
        ocultarPass2.setVisible(false);
        txtPassNuevo.setEchoChar('*');
    }//GEN-LAST:event_ocultarPass2MouseClicked

    private void ocultarPass3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarPass3MouseClicked
        mostrarPass3.setVisible(true);
        ocultarPass3.setVisible(false);
        txtPassConfirmar.setEchoChar('*');
    }//GEN-LAST:event_ocultarPass3MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalirDePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel mostrarPass1;
    public javax.swing.JLabel mostrarPass2;
    public javax.swing.JLabel mostrarPass3;
    public javax.swing.JLabel ocultarPass1;
    public javax.swing.JLabel ocultarPass2;
    public javax.swing.JLabel ocultarPass3;
    public javax.swing.JLabel txtError;
    public javax.swing.JPasswordField txtPassAnterior;
    public javax.swing.JPasswordField txtPassConfirmar;
    public javax.swing.JPasswordField txtPassNuevo;
    // End of variables declaration//GEN-END:variables
}
