
package vistas;


public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuVIsta
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuVentas = new javax.swing.JMenu();
        menuCambiarPass = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO USUARIO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 113, -1, -1));

        lblUser.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(102, 153, 255));
        lblUser.setText("usuario nadamas");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 151, 443, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 15, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 260));

        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menuVentas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuVentas.setForeground(new java.awt.Color(102, 102, 255));
        menuVentas.setText("Ventas");
        menuVentas.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        menuVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVentasMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuVentas);

        menuCambiarPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuCambiarPass.setForeground(new java.awt.Color(102, 102, 255));
        menuCambiarPass.setText("Cambiar contrasenia");
        menuCambiarPass.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        menuCambiarPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCambiarPassMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuCambiarPass);

        menuCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuCerrarSesion.setForeground(new java.awt.Color(102, 102, 255));
        menuCerrarSesion.setText("Cerrar sesion");
        menuCerrarSesion.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        menuCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuCerrarSesion);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVentasMouseClicked
        controlador.Controlador.ItmVentas();
        controlador.Controlador.MostrarUserVenta();
    }//GEN-LAST:event_menuVentasMouseClicked

    private void menuCambiarPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCambiarPassMouseClicked
       controlador.Controlador.ItmCambiarPass();
    }//GEN-LAST:event_menuCambiarPassMouseClicked

    private void menuCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarSesionMouseClicked
       controlador.Controlador.ItmCerrarSesion();
    }//GEN-LAST:event_menuCerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblUser;
    private javax.swing.JMenu menuCambiarPass;
    private javax.swing.JMenu menuCerrarSesion;
    private javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables
}
